In [1]:
import numpy as np
import pandas as pd

In [15]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [16]:
df.head()

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [17]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [18]:
model = Sequential()

model.add(Dense(2, activation='sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.get_weights()

[array([[-0.56655735,  0.35936713],
        [-0.98648274,  0.9761995 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.53752506],
        [-0.75313956]], dtype=float32),
 array([0.], dtype=float32)]

In [21]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [22]:
model.set_weights(new_weights)

In [23]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [24]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [26]:
model.fit(df.iloc[:,0:-1].values, df['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6926
Epoch 2/50
4/4 [==============================] - 0s 8ms/step - loss: 0.6929
Epoch 3/50
4/4 [==============================] - 0s 8ms/step - loss: 0.6927
Epoch 4/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6928
Epoch 5/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6926
Epoch 6/50
4/4 [==============================] - 0s 10ms/step - loss: 0.6926
Epoch 7/50
4/4 [==============================] - 0s 17ms/step - loss: 0.6925
Epoch 8/50
4/4 [==============================] - 0s 9ms/step - loss: 0.6925
Epoch 9/50
4/4 [==============================] - 0s 10ms/step - loss: 0.6926
Epoch 10/50
4/4 [==============================] - 0s 7ms/step - loss: 0.6925
Epoch 11/50
4/4 [==============================] - 0s 7ms/step - loss: 0.6926
Epoch 12/50
4/4 [==============================] - 0s 6ms/step - loss: 0.6927
Epoch 13/50
4/4 [==============================] - 0s 11ms/step - loss