In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.get_weights()

[array([[-1.0267591 , -0.9236629 ],
        [-0.94301474, -0.46597755]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.573563 ],
        [0.5556755]], dtype=float32),
 array([0.], dtype=float32)]

In [9]:
new_weights = [np.array([[0.1, 0.1], [0.1, 0.1]], dtype=np.float32),
               np.array([0., 0.], dtype=np.float32),
               np.array([[0.1], [0.1]], dtype=np.float32),
               np.array([0.], dtype=np.float32)]

In [10]:
model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.8961
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 27.5636
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2355
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 26.9198
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 26.5758
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 26.2095
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8110
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4519
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0671
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6621
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 24.2184
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8009
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [14]:
model.get_weights()

[array([[0.37380734, 0.37380734],
        [0.36574388, 0.36574388]], dtype=float32),
 array([0.2724844, 0.2724844], dtype=float32),
 array([[0.3730908],
        [0.3730908]], dtype=float32),
 array([0.20488425], dtype=float32)]